# Generated by Django 5.0.1 on 2024-01-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_img', models.ImageField(default='profile_img.jpeg', upload_to='profile_images')),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to='users.profile')),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_by_profiles', to='interactions.post')),
                ('posts', models.ManyToManyField(blank=True, related_name='associated_profiles', to='interactions.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_posts', models.ManyToManyField(blank=True, related_name='viewed_by_profiles', to='interactions.post')),
            ],
        ),
    ]
